name: gallery_app_test
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  camera: 0.11.0+1
  external_path: ^1.0.3
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  cross_file_image: ^1.1.0
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

 
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  